### ISSUE TITLE
current version isn't transpiled

### ISSUE THREAD

**Issue by stoeffel** [router5/transition-path#1]
The currently published commonjs file isn't transpiled with babel (see [dist/commonjs/index.js#L66](https://github.com/router5/transition-path/blob/master/dist/commonjs/index.js#L66)).
The build script seams to be broken. Possibly caused by the update to babel 6.

``` bash
$ nr build

> router5.transition-path@2.0.2 build /Users/stoeffel/oss/transition-path
> npm run clean && babel modules --out-dir dist/commonjs


> router5.transition-path@2.0.2 clean /Users/stoeffel/oss/transition-path
> rimraf dist

filenames required for --out-dir
```

I recommend adding the build script to the npm prepublish hook. So it want publish if the build step fails.

This is a major issue, because router5's dependency to this package is `^2.0.1` which will use 2.0.2 now.

// cc @jamuhl

**Comment by troch** [comment]
Thought I had missed something last night :D... plugins and presets. Thanks for raising this.

**Comment by stoeffel** [comment]
Thanks for your quick reaction :+1: 
I guess the version in router5 should be fixed to `2.0.3` too.
To avoid having to update router5 each time you publish a new version of transition-path, you could use something like greenkeeper or tachikoma to automatically update the dependencies.

**Comment by troch** [comment]
It has a ~ or a ^, so it will go to the next patch automatically. Just
remove and re add router5. I had not heard of tachikoma, I'll check it out.

**Comment by stoeffel** [comment]
http://tachikoma.io/

> It has a ~ or a ^, so it will go to the next patch automatically. Just
> remove and re add router5. I had not heard of tachikoma, I'll check it out.

I know. But the `^` is problematic in cases like this. Our complete build crashed because it automatically used 2.0.2. This wouldn't have happened if there was a fixed version. To update to 2.0.3 router5 also would have to update it's version.

**Comment by stoeffel** [comment]
and here the link to http://greenkeeper.io/

> Stop worrying about npm dependencies breaking your build
